# Profile data generated by Devel::NYTProf::Reader
# Version
# Author: Adam Kaplan. More information at http://search.cpan.org/~akaplan
# Format: time,calls,time/call,code
0,1,0,print "This source file will vanish to simulate how the reporting module"
0,0,0,." handles missing files.  You might need to copy me back to test16.p\n";
